FROM node:20-alpine AS build

WORKDIR /app

# Copy root package files because frontend depends on the root package
COPY package*.json ./

# Copy frontend package files
COPY src/frontend/package*.json ./src/frontend/

# Install root dependencies
RUN npm install

# Install frontend dependencies
WORKDIR /app/src/frontend
RUN npm install

# Copy source code
WORKDIR /app
COPY src/frontend ./src/frontend
COPY src ./src

# Build frontend
WORKDIR /app/src/frontend
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/src/frontend/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]